name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/add-to-project
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/tasshi-playground/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
